# Generated by Django 2.0.4 on 2018-04-15 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piazzapolls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_date', models.DateTimeField(verbose_name='datetime answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piazzapolls.Question')),
            ],
        ),
        migrations.RenameModel(
            old_name='Choice',
            new_name='TextResponse',
        ),
    ]
