# Generated by Django 2.0.4 on 2018-04-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piazzapolls', '0002_auto_20180415_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.DateTimeField(verbose_name='datetime answer')),
                ('last_CID', models.IntegerField()),
                ('course_ID', models.IntegerField()),
            ],
        ),
    ]
