# Generated by Django 2.0.4 on 2018-04-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piazzapolls', '0003_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='first_date',
            field=models.DateField(),
        ),
    ]
