# Generated by Django 2.0.4 on 2018-04-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piazzapolls', '0004_auto_20180415_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='information',
            name='course_ID',
            field=models.CharField(max_length=200),
        ),
    ]
