# Generated by Django 2.0.4 on 2018-04-15 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piazzapolls', '0005_auto_20180415_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='keywords',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='information',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='piazzapolls.Information'),
            preserve_default=False,
        ),
    ]
